Algoritmo "siri_cascudo"

Var
   nome, lanche, bebida : caractere

Inicio
   escreva("Digite seu nome: ")
   leia(nome)
   escreva("Escolha seu lanche(Hamburguer de Siri, Algas Secas, Nozes: ")
   leia(lanche)
   escreva("Escolha sua bebida(O², Tinta de Lula, Gosma de Caracol: ")
   leia(bebida)
   
   escreval("Nome: ", nome)
   escreval("Lanche: ", lanche)
   escreval("Bebida: ", bebida)
   escreva("So volte com dinheiro no bolso... quero dizer volte sempre")

Fimalgoritmo